Initial version done with LOTS of help from Cale Gibbard (at Compose Conference 2016).

* TODO:

- Either =?query= or =&query= depending on what is in URL, e.g.,:

http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org

versus

http://localhost:3030/ds/query

- Using =dbpedia= URL above returns good results (see Console in browser) takes a LONG time to render
  - add =LIMIT= / =OFFSET= paging support

- handle data model literals correctly (e.g., @en on strings but not numbers):

#+BEGIN_EXAMPLE
127.0.0.1:3030/ds/query?query=SELECT%20?subject%20?predicate%20%20WHERE%20%7B%20?subject%20?predicate%20%22Excellence%20in%20the%20Community@en%22%20.%7D
#+END_EXAMPLE

* DONE:

- Submit: sending XhrRequest and getting back SPARQL results.
- Aeson parsing and manual collating results.
- Filled in panels with results of submit/SPARQL results.
- first query on panel select works.
- panel refill with selection, done via

#+BEGIN_EXAMPLE
Event XhrResponse = performRequestAsync Event Request
return $ combine Event Request + Event XhrResponse

performRequestsAsync :: (Traversable f, MonadWidget t m) =>
                        Event t (f XhrRequest) -> m (Event t (f XhrResponse))
key : for any type e, we have that (,) e is an instance of Traversable
e.g., : fmap (\x -> (x,x)) on Event t XhrRequest to turn it into Event t (XhrRequest, XhrRequest)
then result will be Event t (XhrRequest, XhrResponse)
Can put anything in the first component of the pair: it will pair that information with the corresponding response
#+END_EXAMPLE

- literals quoted before sending on SPARQL query
- added tracing of SPARQL results
- only set frame =src= if startsWith =http=
- put =@en= on end of literals (to make SPARQL queries work)
- build via work-on
  - https://github.com/reflex-frp/reflex-dom-contrib
#+BEGIN_EXAMPLE
cd .
make wo    # work-on environment
make data  # start fuseki and TCPMon
make c     # configure
make b     # build
make v     # visit the page in browser
#+END_EXAMPLE
- use real URL Encoder
- placing stuff via CSS
  - http://stackoverflow.com/a/20179337/814846 (scroll down to end of answer)
- do not change iframe =src= on non-URLs
- expand/contract dropdown contents
- sort dropdown contents (via ordered keys in Map)
- anchor opens current selection in new tab when clicked

* wiring diagram

file:./wiring-diagram.jpg

