Initial version done with LOTS of help from Cale Gibbard (at Compose Conference 2016).

* Current state:

- Submit: sending XhrRequest and getting back SPARQL results.
- Aeson parsing and manual collating results.
- Filled in panels with results of submit/SPARQL results.
- first query on panel select works.

** start TCOMon + fuseki + load data

file:///~/ftptmp/ebooks-music-pics/tech/programming-language/haskell/interview/0-Notes.org

** Build via try-reflex

[[https://github.com/ryantrinkle/try-reflex]]

cd ~/try-reflex
./try-reflex
# RTB.hs is linked here
ghcjs --make RTB.hs

file:///Users/carr/try-reflex/RTB.jsexe/index.html

** DONE

Traverse sparql results to build Resp data structure.

See haskell/playpen/aeson-playground/src/AesonAST.hs

- sparql-json.hs
- at.hs

* Next:

- Panel refill or dont touch if not included in results
  - current state: causes further queries after a panel select to fail because of empty panel
- expand/contract panel displays

* TODO:

- build via work-on
- rdf-triple-browser.cabal
- build.sh
- use real UrlEncoder

* Misc:

GET http://127.0.0.1:3030/ds/query?query=%20SELECT%20%20%3Fx0%20%3Fx1%20%3Fx2%20WHERE%20%7B%3Chttp%3A%2F%2Fopenhc.org%2Fdata%2Fevent%2FSlug_Magazine_Salt_Lake_City_Utah%3E%20%3Fx1%20%3Fx2%20.%7D%20Limit%20100

GET http://127.0.0.1:3030/ds/query?query= SELECT  ?x0 ?x1 ?x2 WHERE {<http://openhc.org/data/event/Slug_Magazine_Salt_Lake_City_Utah> ?x1 ?x2 .} Limit 100
