  x = fromList
      [("results"
       ,Object
        (fromList
         [("bindings"
          ,Array [Object  (fromList [("object",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://xmlns.com/foaf/0.1/Organization") ]))
                                    ,("subject", Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/data/event/University_of_Utah_Humanities_Happy_Hour")]))
                                    ,("predicate",Object (fromList [("type",String "uri")
                                                                   ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")]))])
                 ,Object  (fromList [("object",Object (fromList [("type",String "literal")
                                                                ,("xml:lang",String "en")
                                                                ,("value",String "University of Utah Humanities Happy Hour")]))
                                    ,("subject",Object (fromList [("type",String "uri")
                                                                 ,("value",String "http://openhc.org/data/event/University_of_Utah_Humanities_Happy_Hour")]))
                                    ,("predicate",Object (fromList [("type",String "uri")
                                                                   ,("value",String "http://xmlns.com/foaf/0.1/name")]))])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")]))
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Music_Garage_Utah")]))
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")]))])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Music Garage")]))
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Music_Garage_Utah")]))
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")]))])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://musicgarage.org/")   ]))
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Music_Garage_Utah")]))
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")]))])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("value",String "801-577-2263")]))
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Music_Garage_Utah")]))
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/phone")]))])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")]))
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Intermountain_Acoustic_Music_Association")]))
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")]))])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Intermountain Acoustic Music Association")         ])                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Intermountain_Acoustic_Music_Association")          ])       )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])    )        ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://www.iamaweb.org/")    ])    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Intermountain_Acoustic_Music_Association")                                                    ])                        )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")
                                                                  ])                                  )        ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")
                                                               ])                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/City_Art_Poetry_Utah")           ])                        )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")                      ])           )             ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "City Art")
                                                               ])                     )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/City_Art_Poetry_Utah")
                                                                ])        )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])             )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://slcityart.org/")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/City_Art_Poetry_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("value",String "84068")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.geonames.org/ontology#postalCode")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Park City")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#city")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://www.mountaintownmusic.org/")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("value",String "brian@mountaintownstages.com")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/email")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("value",String "435-901-SONG")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/phone")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Utah")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#area")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Mountain Town Music")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "P.O. Box 680896")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#address")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "United States")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Mountain_Town_Stages_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#country")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Salt Lake Community College")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "4600 South Redwood Road")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#address")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Salt Lake City")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#city")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Utah")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#area")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("value",String "84123")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.geonames.org/ontology#postalCode")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "United States")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://openhc.org/schemas/event-2009-10-14.owl#country")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("value",String "801-957-SLCC (957-7522)")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/phone")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://www.slcc.edu/")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Community_College")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Excellence_in_the_Community_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Excellence in the Community")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Excellence_in_the_Community_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://www.excellenceconcerts.org/")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Excellence_in_the_Community_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Symphony_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "The Salt Lake Symphony")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Symphony_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://www.saltlakesymphony.org/")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Salt_Lake_Symphony_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/University_of_Utah_Creative_Writing_Program")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "The University of Utah Creative Writing Program")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/University_of_Utah_Creative_Writing_Program")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://www.saltlakesymphony.org/pix/guests/Robert_Baldwin-3.gif")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/University_of_Utah_Creative_Writing_Program")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/depiction")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://xmlns.com/foaf/0.1/Organization")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Slug_Magazine_Salt_Lake_City_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "literal")
                                                               ,("xml:lang",String "en")
                                                               ,("value",String "Slug Magazine")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Slug_Magazine_Salt_Lake_City_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/name")
                                                                  ])
                                    )
                                   ])
                 ,Object (fromList [("object",Object (fromList [("type",String "uri")
                                                               ,("value",String "http://www.slugmag.com/")
                                                               ])
                                    )
                                   ,("subject",Object (fromList [("type",String "uri")
                                                                ,("value",String "http://openhc.org/data/event/Slug_Magazine_Salt_Lake_City_Utah")
                                                                ])
                                    )
                                   ,("predicate",Object (fromList [("type",String "uri")
                                                                  ,("value",String "http://xmlns.com/foaf/0.1/homepage")
                                                                  ])
                                    )
                                   ])
                 ])
         ])
       )
      ,("head",Object (fromList [("vars",Array [String "subject",String "predicate",String "object"])
                                ])
       )
      ]
